@{ Name='compose'; Version='1.0.0'; RootModule='Plot.Compose.psm1'; Dependencies=@('process'); Steps=@{
'config'=@{Command='Invoke-PlotComposeConfig';Parameters=@{ProjectName=@{Type='string';Required=$true}; Files=@{Type='array';Required=$true}; Directory=@{Type='string';Default='.'}; EnvFiles=@{Type='array';Default=@()}; Profiles=@{Type='array';Default=@()}; Services=@{Type='array';Default=@()}; Arguments=@{Type='array';Default=@();Secret=$true}; Environment=@{Type='object';Default=@{};Secret=$true}; TimeoutSeconds=@{Type='int';Default=300;Minimum=1;Maximum=86400};}}
'pull'=@{Command='Invoke-PlotComposePull';Parameters=@{ProjectName=@{Type='string';Required=$true}; Files=@{Type='array';Required=$true}; Directory=@{Type='string';Default='.'}; EnvFiles=@{Type='array';Default=@()}; Profiles=@{Type='array';Default=@()}; Services=@{Type='array';Default=@()}; Arguments=@{Type='array';Default=@();Secret=$true}; Environment=@{Type='object';Default=@{};Secret=$true}; TimeoutSeconds=@{Type='int';Default=300;Minimum=1;Maximum=86400};}}
'build'=@{Command='Invoke-PlotComposeBuild';Parameters=@{ProjectName=@{Type='string';Required=$true}; Files=@{Type='array';Required=$true}; Directory=@{Type='string';Default='.'}; EnvFiles=@{Type='array';Default=@()}; Profiles=@{Type='array';Default=@()}; Services=@{Type='array';Default=@()}; Arguments=@{Type='array';Default=@();Secret=$true}; Environment=@{Type='object';Default=@{};Secret=$true}; TimeoutSeconds=@{Type='int';Default=300;Minimum=1;Maximum=86400};}}
'up'=@{Command='Invoke-PlotComposeUp';Parameters=@{ProjectName=@{Type='string';Required=$true}; Files=@{Type='array';Required=$true}; Directory=@{Type='string';Default='.'}; EnvFiles=@{Type='array';Default=@()}; Profiles=@{Type='array';Default=@()}; Services=@{Type='array';Default=@()}; Arguments=@{Type='array';Default=@();Secret=$true}; Environment=@{Type='object';Default=@{};Secret=$true}; TimeoutSeconds=@{Type='int';Default=300;Minimum=1;Maximum=86400};}}
'ps'=@{Command='Invoke-PlotComposePs';Parameters=@{ProjectName=@{Type='string';Required=$true}; Files=@{Type='array';Required=$true}; Directory=@{Type='string';Default='.'}; EnvFiles=@{Type='array';Default=@()}; Profiles=@{Type='array';Default=@()}; Services=@{Type='array';Default=@()}; Arguments=@{Type='array';Default=@();Secret=$true}; Environment=@{Type='object';Default=@{};Secret=$true}; TimeoutSeconds=@{Type='int';Default=300;Minimum=1;Maximum=86400};}}
'logs'=@{Command='Invoke-PlotComposeLogs';Parameters=@{ProjectName=@{Type='string';Required=$true}; Files=@{Type='array';Required=$true}; Directory=@{Type='string';Default='.'}; EnvFiles=@{Type='array';Default=@()}; Profiles=@{Type='array';Default=@()}; Services=@{Type='array';Default=@()}; Arguments=@{Type='array';Default=@();Secret=$true}; Environment=@{Type='object';Default=@{};Secret=$true}; TimeoutSeconds=@{Type='int';Default=300;Minimum=1;Maximum=86400};}}
'stop'=@{Command='Invoke-PlotComposeStop';Parameters=@{ProjectName=@{Type='string';Required=$true}; Files=@{Type='array';Required=$true}; Directory=@{Type='string';Default='.'}; EnvFiles=@{Type='array';Default=@()}; Profiles=@{Type='array';Default=@()}; Services=@{Type='array';Default=@()}; Arguments=@{Type='array';Default=@();Secret=$true}; Environment=@{Type='object';Default=@{};Secret=$true}; TimeoutSeconds=@{Type='int';Default=300;Minimum=1;Maximum=86400};}}
'down'=@{Command='Invoke-PlotComposeDown';Parameters=@{ProjectName=@{Type='string';Required=$true}; Files=@{Type='array';Required=$true}; Directory=@{Type='string';Default='.'}; EnvFiles=@{Type='array';Default=@()}; Profiles=@{Type='array';Default=@()}; Services=@{Type='array';Default=@()}; Arguments=@{Type='array';Default=@();Secret=$true}; Environment=@{Type='object';Default=@{};Secret=$true}; TimeoutSeconds=@{Type='int';Default=300;Minimum=1;Maximum=86400};}}
}}
