@{ Name='sqlserver'; Version='1.0.0'; RootModule='Plot.SqlServer.psm1';  Steps=@{
'query'=@{Command='Invoke-PlotSqlQuery';Parameters=@{ConnectionString=@{Type='string';Required=$true;Secret=$true}; ConnectTimeoutSeconds=@{Type='int';Default=15;Minimum=1;Maximum=300}; CommandTimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=86400};Query=@{Type='string';Required=$true;Secret=$true}; Parameters=@{Type='object';Default=@{};Secret=$true}; MaxRows=@{Type='int';Default=10000;Minimum=1;Maximum=1000000};}}
'execute'=@{Command='Invoke-PlotSqlExecute';Parameters=@{ConnectionString=@{Type='string';Required=$true;Secret=$true}; ConnectTimeoutSeconds=@{Type='int';Default=15;Minimum=1;Maximum=300}; CommandTimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=86400};Query=@{Type='string';Default='';Secret=$true}; Path=@{Type='string';Default=''}; Parameters=@{Type='object';Default=@{};Secret=$true};}}
'backup'=@{Command='Invoke-PlotSqlBackup';Parameters=@{ConnectionString=@{Type='string';Required=$true;Secret=$true}; ConnectTimeoutSeconds=@{Type='int';Default=15;Minimum=1;Maximum=300}; CommandTimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=86400};Database=@{Type='string';Required=$true};Path=@{Type='string';Required=$true}; CopyOnly=@{Type='bool';Default=$true}; Initialize=@{Type='bool';Default=$false};}}
'restore'=@{Command='Invoke-PlotSqlRestore';Parameters=@{ConnectionString=@{Type='string';Required=$true;Secret=$true}; ConnectTimeoutSeconds=@{Type='int';Default=15;Minimum=1;Maximum=300}; CommandTimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=86400};Database=@{Type='string';Required=$true};Path=@{Type='string';Required=$true}; Moves=@{Type='object';Required=$true}; Replace=@{Type='bool';Default=$false}; BackupSet=@{Type='int';Default=1;Minimum=1};}}
'create'=@{Command='Invoke-PlotSqlCreate';Parameters=@{ConnectionString=@{Type='string';Required=$true;Secret=$true}; ConnectTimeoutSeconds=@{Type='int';Default=15;Minimum=1;Maximum=300}; CommandTimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=86400};Database=@{Type='string';Required=$true};RecoveryModel=@{Type='string';Default='SIMPLE';ValidateSet=@('SIMPLE','FULL','BULK_LOGGED')};}}
'drop'=@{Command='Invoke-PlotSqlDrop';Parameters=@{ConnectionString=@{Type='string';Required=$true;Secret=$true}; ConnectTimeoutSeconds=@{Type='int';Default=15;Minimum=1;Maximum=300}; CommandTimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=86400};Database=@{Type='string';Required=$true};}}
'configure-file'=@{Command='Invoke-PlotSqlConfigureFile';Parameters=@{ConnectionString=@{Type='string';Required=$true;Secret=$true}; ConnectTimeoutSeconds=@{Type='int';Default=15;Minimum=1;Maximum=300}; CommandTimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=86400};Database=@{Type='string';Required=$true};LogicalName=@{Type='string';Required=$true}; SizeMb=@{Type='int';Required=$true;Minimum=1}; MaxSizeMb=@{Type='int';Required=$true;Minimum=1}; GrowthMb=@{Type='int';Default=64;Minimum=1};}}
'user'=@{Command='Invoke-PlotSqlUser';Parameters=@{ConnectionString=@{Type='string';Required=$true;Secret=$true}; ConnectTimeoutSeconds=@{Type='int';Default=15;Minimum=1;Maximum=300}; CommandTimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=86400};Database=@{Type='string';Required=$true};Action=@{Type='string';Required=$true;ValidateSet=@('create','drop')}; UserName=@{Type='string';Required=$true}; LoginName=@{Type='string';Default=''}; Roles=@{Type='array';Default=@()};}}
'login'=@{Command='Invoke-PlotSqlLogin';Parameters=@{ConnectionString=@{Type='string';Required=$true;Secret=$true}; ConnectTimeoutSeconds=@{Type='int';Default=15;Minimum=1;Maximum=300}; CommandTimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=86400};Action=@{Type='string';Required=$true;ValidateSet=@('create','drop')}; LoginName=@{Type='string';Required=$true}; Password=@{Type='string';Default='';Secret=$true};}}
'wait'=@{Command='Invoke-PlotSqlWait';Parameters=@{ConnectionString=@{Type='string';Required=$true;Secret=$true}; ConnectTimeoutSeconds=@{Type='int';Default=15;Minimum=1;Maximum=300}; CommandTimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=86400};TimeoutSeconds=@{Type='int';Default=60;Minimum=1;Maximum=3600}; IntervalMilliseconds=@{Type='int';Default=1000;Minimum=1;Maximum=60000};}}
}}
